/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.IControlador;
import logica.TipoEstado;
import static logica.TipoEstado.confirmada;
import static logica.TipoEstado.rechazada;

/**
 *
 * @author natil
 */
public class AceptarRechazarActividadTuristica extends javax.swing.JInternalFrame {
    private IControlador control;
    /**
     * Creates new form AceptarRechazarActividadTuristica
     */
    public AceptarRechazarActividadTuristica(IControlador icu) {
        control = icu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbActividades = new javax.swing.JComboBox<>();
        btnConfirmar = new javax.swing.JButton();
        btnRechazar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Confirmar/Rechazar Actividad Turistica");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Seleccione Actividad:");

        btnConfirmar.setText("Confirmar Actividad");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnRechazar.setText("Rechazar Actividad");
        btnRechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmbActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnRechazar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnRechazar))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazarActionPerformed
        // TODO add your handling code here:
       try{
        String nombreActividad = (String) cmbActividades.getSelectedItem();
        control.cambiarEstadoActividad(nombreActividad, rechazada);
        JOptionPane.showMessageDialog(null, "Rechazo de Actividad realizada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
       }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo modificar. No se seleccionó actividad.", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnRechazarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        //Cargo combo box de actividades agregadas
        cmbActividades.removeAllItems();
        ArrayList<String> actividadesAgregadas = control.listaActividadesPorEstado(TipoEstado.agregada);
        for (String aAgr : actividadesAgregadas) {
            cmbActividades.addItem(aAgr);
        }
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        try{
            String nombreActividad = (String) cmbActividades.getSelectedItem();
            control.cambiarEstadoActividad(nombreActividad, confirmada);
            JOptionPane.showMessageDialog(null, "Confirmacion de Actividad realizada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
       }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No se pudo modificar. No se seleccionó actividad.", "Error", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRechazar;
    private javax.swing.JComboBox<String> cmbActividades;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
