/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import logica.Controlador;
import logica.IControlador;
/**
 *
 * @author natil
 */
public class AgregarActividadTuristicaPaquete extends javax.swing.JInternalFrame {
    private IControlador control;
    
    /**
     * Creates new form AgregarActividadTuristicaPaquete
     */
    public AgregarActividadTuristicaPaquete(IControlador icu) {
        control = icu;
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        paqueteAgregarActividadPaquete = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        departamentoAgregarActividadPaquete = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        paqueteAgregarActividadTuristica = new javax.swing.JComboBox<>();
        aceptarAgregarActividadPaquete = new javax.swing.JButton();
        cancelarAgregarActividadPaquete = new javax.swing.JButton();

        setClosable(true);
        setTitle("Agregar Actividad Turistica a Paquete");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Seleccione paquete turistico:");

        paqueteAgregarActividadPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lista paquete turistico" }));

        jLabel2.setText("Seleccionar departamento:");

        departamentoAgregarActividadPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lista departamentos" }));
        departamentoAgregarActividadPaquete.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departamentoAgregarActividadPaqueteItemStateChanged(evt);
            }
        });

        jLabel3.setText("Agregar actividad turistica:");

        paqueteAgregarActividadTuristica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "lista actividad turisticas" }));
        paqueteAgregarActividadTuristica.setSelectedIndex(-1);

        aceptarAgregarActividadPaquete.setText("Aceptar");
        aceptarAgregarActividadPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarAgregarActividadPaqueteActionPerformed(evt);
            }
        });

        cancelarAgregarActividadPaquete.setText("Limpiar");
        cancelarAgregarActividadPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarAgregarActividadPaqueteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(paqueteAgregarActividadPaquete, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(departamentoAgregarActividadPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(paqueteAgregarActividadTuristica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(aceptarAgregarActividadPaquete)
                        .addGap(85, 85, 85)
                        .addComponent(cancelarAgregarActividadPaquete)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(paqueteAgregarActividadPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(departamentoAgregarActividadPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(paqueteAgregarActividadTuristica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarAgregarActividadPaquete)
                    .addComponent(cancelarAgregarActividadPaquete))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        paqueteAgregarActividadPaquete.removeAllItems();
        ArrayList<String> nombresPaquete = control.listaPaquetesSinCompra();
        for (String p : nombresPaquete) {
            paqueteAgregarActividadPaquete.addItem(p);

        }
        departamentoAgregarActividadPaquete.removeAllItems();
        ArrayList<String> nicks = control.listaDeptos();
        for (int i = 0; i < nicks.size(); i++) {
            departamentoAgregarActividadPaquete.addItem(nicks.get(i));
        }
    }//GEN-LAST:event_formComponentShown

    private void limpiarAgregarActividadPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarAgregarActividadPaqueteActionPerformed
        paqueteAgregarActividadPaquete.setSelectedIndex(-1);
        departamentoAgregarActividadPaquete.setSelectedIndex(-1);
        paqueteAgregarActividadTuristica.setSelectedIndex(-1);
    }//GEN-LAST:event_limpiarAgregarActividadPaqueteActionPerformed

    private void departamentoAgregarActividadPaqueteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departamentoAgregarActividadPaqueteItemStateChanged
      
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String departamentoSeleccionado = (String) departamentoAgregarActividadPaquete.getSelectedItem();
        List<String> actividades = control.listaActividadesTuristicasConfirmadas(departamentoSeleccionado);

           paqueteAgregarActividadTuristica.removeAllItems();
           
            for (String actividad : actividades) {
                paqueteAgregarActividadTuristica.addItem(actividad);
            }
    
}
    }//GEN-LAST:event_departamentoAgregarActividadPaqueteItemStateChanged

    private void aceptarAgregarActividadPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarAgregarActividadPaqueteActionPerformed
    String paqueteSeleccionado = (String) paqueteAgregarActividadPaquete.getSelectedItem();
    
    String actividadSeleccionada = (String) paqueteAgregarActividadTuristica.getSelectedItem();
    
    try{
    control.asignarActividadPaquete(paqueteSeleccionado, actividadSeleccionada);
    JOptionPane.showMessageDialog(null, "Se agrego correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }catch (Exception ex){
       JOptionPane.showMessageDialog(null, "Ha ocurrido un error", "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_aceptarAgregarActividadPaqueteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarAgregarActividadPaquete;
    private javax.swing.JButton cancelarAgregarActividadPaquete;
    private javax.swing.JComboBox<String> departamentoAgregarActividadPaquete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> paqueteAgregarActividadPaquete;
    private javax.swing.JComboBox<String> paqueteAgregarActividadTuristica;
    // End of variables declaration//GEN-END:variables
}
