/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import logica.DTTurista;
import logica.Controlador;
import logica.DTActividad;
import logica.DTImagenPerfil;
import logica.DTSalidaTuristica;
import logica.IControlador;
import logica.ImagenPerfil;

/**
 *
 * @author natil
 */
public class ConsultaUsuarioTurista extends javax.swing.JInternalFrame {

    private IControlador control;

    /**
     * Creates new form ConsultaUsuarioTurista2
     */
    public ConsultaUsuarioTurista(String nickname, IControlador icu) {
        control = icu;
        initComponents();
        cargarDatosTurista(nickname);
        cargarSalidasDeTurista(nickname);
        cargarActividadesDelTurista(nickname);
        mostrarImagenPerfil(nickname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtFNacimiento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cmbActividades = new javax.swing.JComboBox<>();
        txtApellido = new javax.swing.JTextField();
        btnVerActividad = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        cmbSalidas = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        btnVerSalida = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelImagen = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setClosable(true);
        setTitle("Consulta Datos Turista");
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Datos turista:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 14, 95, 21);

        jLabel16.setText("Correo electronico:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 160, 140, 21);

        txtFNacimiento.setEditable(false);
        getContentPane().add(txtFNacimiento);
        txtFNacimiento.setBounds(168, 189, 260, 29);

        jLabel17.setText("F. de nacimiento:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(6, 192, 150, 21);

        jLabel11.setText("Actividad Turistica");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(6, 362, 140, 21);

        txtNombre.setEditable(false);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(148, 87, 280, 29);

        getContentPane().add(cmbActividades);
        cmbActividades.setBounds(148, 359, 330, 29);

        txtApellido.setEditable(false);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(148, 127, 280, 29);

        btnVerActividad.setText("Ver");
        btnVerActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActividadActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerActividad);
        btnVerActividad.setBounds(490, 359, 90, 29);

        txtCorreo.setEditable(false);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(170, 160, 260, 29);

        jLabel2.setText("nickname:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 50, 100, 21);

        jLabel18.setText("Salidas Turisticas");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(6, 323, 130, 21);

        txtNickname.setEditable(false);
        getContentPane().add(txtNickname);
        txtNickname.setBounds(148, 47, 280, 29);

        getContentPane().add(cmbSalidas);
        cmbSalidas.setBounds(148, 320, 330, 29);

        jLabel13.setText("Nacionalidad:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(6, 226, 110, 21);

        btnVerSalida.setText("Ver");
        btnVerSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerSalida);
        btnVerSalida.setBounds(490, 320, 90, 29);

        jLabel14.setText("Nombre:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(6, 90, 90, 21);

        txtNacionalidad.setEditable(false);
        getContentPane().add(txtNacionalidad);
        txtNacionalidad.setBounds(127, 223, 301, 29);

        jLabel15.setText("Apellido:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(6, 130, 90, 21);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Inscripto a:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 287, 110, 21);

        labelImagen.setBackground(new java.awt.Color(51, 51, 51));
        labelImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(labelImagen);
        labelImagen.setBounds(480, 50, 300, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerSalidaActionPerformed
        if (cmbSalidas.getSelectedIndex() != -1) {

            String nombreSalida = (String) cmbSalidas.getSelectedItem();

            ConsultaDeSalidaTuristica verConsultaDeSalidaTuristica = new ConsultaDeSalidaTuristica(nombreSalida, control);
            getParent().add(verConsultaDeSalidaTuristica);
            verConsultaDeSalidaTuristica.show();
        }
    }//GEN-LAST:event_btnVerSalidaActionPerformed

    private void btnVerActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActividadActionPerformed
        if (cmbActividades.getSelectedIndex() != -1) {
            String nombreActividad = (String) cmbActividades.getSelectedItem();

            ConsultaActividadTuristica verConsultaActividadTuristica = new ConsultaActividadTuristica(nombreActividad, control);
            getParent().add(verConsultaActividadTuristica);
            verConsultaActividadTuristica.show();
        }
    }//GEN-LAST:event_btnVerActividadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerActividad;
    private javax.swing.JButton btnVerSalida;
    private javax.swing.JComboBox<String> cmbActividades;
    private javax.swing.JComboBox<String> cmbSalidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelImagen;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFNacimiento;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosTurista(String nickname) {
        DTTurista t = control.traerDTTurista(nickname);

        txtNickname.setText(t.getNickname());
        txtNombre.setText(t.getNombre());
        txtApellido.setText(t.getApellido());
        txtNacionalidad.setText(t.getNacionalidad());
        txtCorreo.setText(t.getCorreo());

        txtFNacimiento.setText(t.getfNacimiento());

    }

    private void cargarSalidasDeTurista(String nickname) {

        ArrayList<DTSalidaTuristica> listaSalidasDeTurista = control.traerInscSalidasDeTurista(nickname);

        for (DTSalidaTuristica dt : listaSalidasDeTurista) {
            cmbSalidas.addItem(dt.getNombre());
        }
    }

    private void cargarActividadesDelTurista(String nickname) {

        ArrayList<DTActividad> listaActividadesDeTurista = control.traerInscActividadesDeTurista(nickname);
        for (DTActividad dt : listaActividadesDeTurista) {
            cmbActividades.addItem(dt.getNombre());
        }

    }

    public void mostrarMensaje(String mensaje, String tipo, String titulo) {
        JOptionPane optionPane = new JOptionPane(mensaje);
        if (tipo.equals("Info")) {
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        } else if (tipo.equals("Error")) {
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);

    }

    public void mostrarImagenPerfil(String nickname) {
        try {
            DTImagenPerfil imagen = control.buscarImagenPorNickname(nickname);

            if (imagen != null) {
                // Obtener el directorio de trabajo actual
                String directorioTrabajo = System.getProperty("user.home");

                // Definir una carpeta para las imágenes dentro del directorio de trabajo
                String carpetaImagenes = directorioTrabajo + File.separator + "images";

                // Utilizar la carpeta para construir la ruta completa
                String rutaCompleta = carpetaImagenes + File.separator + imagen.getNombre();
                
                BufferedImage imagenCargada = ImageIO.read(new File(rutaCompleta));

                // Escalar la imagen al tamaño de la etiqueta (labelImagen)
                int anchoEtiqueta = labelImagen.getWidth();
                int altoEtiqueta = labelImagen.getHeight();
                Image imagenEscalada = imagenCargada.getScaledInstance(anchoEtiqueta, altoEtiqueta, Image.SCALE_SMOOTH);

                ImageIcon imagenPerfil = new ImageIcon(imagenEscalada);

                // Supongamos que 'labelImagen' es el JLabel en el que quieres mostrar la imagen
                labelImagen.setIcon(imagenPerfil);
                labelImagen.setVisible(true);
            } else {
                // Manejar el caso en el que no se encuentra la imagen
                labelImagen.setVisible(false); // Oculta el JLabel si no hay imagen
                JOptionPane.showMessageDialog(null, "No se encontró la imagen de perfil.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (IOException e) {
            e.printStackTrace();
            // Manejar errores al cargar la imagen desde el archivo
            JOptionPane.showMessageDialog(null, "Error al cargar la imagen.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            // Manejar otras excepciones generales
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

}
